name: challenge2

on: push

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
        - run: date
    job2:
        name: job2
        runs-on: windows-latest
        steps:
        - run: date
           
    job3:
        name: job3
        runs-on: macos-latest
        steps:
        - run: date
    job4:
        name: job4
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
        - run: date
