name: artifact workflow

on: [push]

jobs:
  make-artifact:
    env:
      ARTIFACT_NAME: 'DanielArtifact'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Create artifact
        uses: actions/upload-artifact@v1.0.0
        with:
            name: ${{ env.ARTIFACT_NAME }}
            path: oldactions
